apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwOi8vMTUuMTY0LjEyLjU0OjUwMDAvdjEvIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Im1lZ2F6b25lMDAhIiwiYXV0aCI6IllXUnRhVzQ2YldWbllYcHZibVV3TUNFPSJ9fX0=
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
